// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNONnSeixxOrKJh9K7Yx3-RU-smxW-588',
    appId: '1:724875757506:web:67f961fb7c9f3c4ba4785b',
    messagingSenderId: '724875757506',
    projectId: 'app1-9e840',
    authDomain: 'app1-9e840.firebaseapp.com',
    storageBucket: 'app1-9e840.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg-3YaLNEBa3ngDzYtEt_-Gdsw2_yynF8',
    appId: '1:724875757506:android:f9afb2a56094dce9a4785b',
    messagingSenderId: '724875757506',
    projectId: 'app1-9e840',
    storageBucket: 'app1-9e840.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChtr9uHdYF7XN3_vCD6ZkmSG5eEodeGk4',
    appId: '1:724875757506:ios:79632d5a3c9c7dd4a4785b',
    messagingSenderId: '724875757506',
    projectId: 'app1-9e840',
    storageBucket: 'app1-9e840.firebasestorage.app',
    iosBundleId: 'com.example.finxFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChtr9uHdYF7XN3_vCD6ZkmSG5eEodeGk4',
    appId: '1:724875757506:ios:79632d5a3c9c7dd4a4785b',
    messagingSenderId: '724875757506',
    projectId: 'app1-9e840',
    storageBucket: 'app1-9e840.firebasestorage.app',
    iosBundleId: 'com.example.finxFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNONnSeixxOrKJh9K7Yx3-RU-smxW-588',
    appId: '1:724875757506:web:5d766e34cd888aa9a4785b',
    messagingSenderId: '724875757506',
    projectId: 'app1-9e840',
    authDomain: 'app1-9e840.firebaseapp.com',
    storageBucket: 'app1-9e840.firebasestorage.app',
  );
}
